objective: # Choose loss type
  - Nonnegative Matrix Factorization[share_init=True]
dataset: # dataset to run benchmark on
  - simulated
solver: # list of example solvers to do benchmark
  - mu
  # - mu_aao
  - mu_burg
  # - fpa
  # - admm[rho=[1,10,100]]
  - som
  # - scalar_newton
  - newton[iter_HALS=[5], descent=[False],n_inner_iter=[5]] 
  # - hals[iter_HALS=[10]]

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1

timeout: 5